services:
  gateway-service:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    container_name: gateway-service
    ports:
      - "8080:8080"
    environment:
      - ACCOUNT_SERVICE_URL=http://account-service:8081
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4318/v1/traces
      - JAVA_TOOL_OPTIONS=-XX:TieredStopAtLevel=1
    restart: always
    volumes:
      - ./dumps/gateway:/var/log/dumps
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
    depends_on:
      - account-service
      - tempo

  account-service:
    build:
      context: ./account-service
      dockerfile: Dockerfile
    container_name: account-service
    ports:
      - "8081:8081"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4318/v1/traces
      - JAVA_TOOL_OPTIONS=-XX:TieredStopAtLevel=1
    restart: always
    volumes:
      - ./dumps/account:/var/log/dumps
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
    depends_on:
      - tempo

  tempo:
    image: grafana/tempo:2.3.0
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./docker/tempo/tempo.yml:/etc/tempo.yaml
    ports:
      - "14268:14268" # jaeger ingest
      - "3200:3200" # tempo http port
      - "4317:4317" # otlp grpc
      - "4318:4318" # otlp http
      - "9411:9411" # zipkin

  prometheus:
    image: prom/prometheus:v2.47.0
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - gateway-service
      - account-service

  loki:
    image: grafana/loki:2.9.1
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./docker/loki/loki.yml:/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.9.1
    container_name: promtail
    volumes:
      - ./docker/promtail/promtail.yml:/etc/promtail/config.yml
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki

  mailpit:
    image: axllent/mailpit:v1.10.1
    container_name: mailpit
    ports:
      - "8025:8025" # Web UI
      - "1025:1025" # SMTP port

  grafana:
    image: grafana/grafana:10.1.5
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=mailpit:1025
      - GF_SMTP_FROM_ADDRESS=grafana@ledger.local
      - GF_SMTP_SKIP_VERIFY=true
    volumes:
      - ./docker/grafana/provisioning/datasources/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./docker/grafana/provisioning/dashboards/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./docker/grafana/provisioning/alerting/alerting.yml:/etc/grafana/provisioning/alerting/alerting.yml
      - ./docker/grafana/dashboards/dashboard.json:/var/lib/grafana/dashboards/dashboard.json
    depends_on:
      - prometheus
      - loki
      - tempo
      - mailpit
    extra_hosts:
      - "host.docker.internal:host-gateway"
