plugins {
    id 'java-library'
}

dependencies {
    api 'org.springframework.boot:spring-boot-starter-web'
    api 'org.springframework.boot:spring-boot-starter-validation'
    api 'org.springframework.boot:spring-boot-starter-aop'
    
    // Micrometer / OpenTelemetry Tracing standard dependencies
    api 'io.micrometer:micrometer-tracing-bridge-otel'
    api 'io.micrometer:micrometer-core'
    api 'io.opentelemetry:opentelemetry-api'
}
